git:
  depth: 1
os:
- osx
language: node_js
node_js:
- 6.7.0
install:
- npm install
- cd script && npm install && cd ..
- sh travis_before_script.sh
script: script/build --compress-artifacts
cache:
  directories:
  - electron
  - node_modules
  - apm/node_modules
  - script/node_modules
  - attach-package/node_modules
  - ~/.thera/compile-cache
notifications:
  email:
    recipients:
    - huc1011@gmail.com
    - hzdengxu@163.com
    - 1032419360@qq.com
    on_failure: always
deploy:
  provider: bintray
  file: bintray_depoly_description.json
  user: nickolasomg
  key:
    secure: SzTNSoNEtOOVLVTATMbs26F6RJdwLdHjZo5eyjirN87sYY0jdFc7VXUPhw0zk8WZKE2WXNqDpg3e+xhRdbhc4R/PcH35UtpExBoM6Ml0kKeOy4s9jbpJq0HpQLPs2k8RJB46GfRPpI5IzEfJH/z4PngL7OXKH+XHgyoRmMIr9eMCpOMnQQYQubaD1DEmw6gOzQrpUNmH5dEGwz/WCzdqe6R76lioxixqmhoLbH+xxNWeE+a5hgfH4wD+sN6tg6f9a2aMMgHifGD3mGzshmPVThZqPk4TXWqlsYHWa10ybtGMLGQPoMmCiIljOmVa/0ew+ppA2IBFvd31Z66HDs87raudFqGw/QegA35Lt4EQgCXPwMw13Dd6cxCatU6A27NHkMOktrEA4q8P6X7vKreC1I2pnH8jtrv0b02CxjkanVSNdrxEAqatznxxzUV05xRr7DSj70c2nDioxt7Cfwgph+1OkqcR6eNUIzVKRNUwutttqybbaw+mW+2f2b7Oj6M+KE1GOSKjfC4vPPu3Z4ba58vT3WpojDw4kKQuJKKoqNoMu3X0IkVWjQCw3Vursm/M9nZu75ov5nANwe+2YkO3Pfe1NHCdxvjzwFMF2ETPbhCXWslmpb79/srfdyfLgWilW61szbXTtahuumpi124It99w/3xOGtyDfgYdwXkFaCA=
  on:
    all_branches: true
63e68213843f9966fe84a21855e1379f53b83fef:
  secure: pj/zsk5iuN1NU4HvLoi3SYAnYEaAiSRaYpQ+DQobBgGNetI6TD/FpyxrG2MN0IAp38n5ixDbwQiIoyQLu7Ps9U0MGeGVvdmt82+JTYfTFHGz7EQg2T3pmrOqjukTXz7jtXYrFlYYGCcEF8Z9Fs7DP/i+pwMDG/e5hdcWrUIaT8omNWT0+7NtZtrp76TeKAu1ifQsIRkod9N5dHpaL93R/+0dA+N7BWInYUVuoRESXhr6FU/8Tmr6Gu8+0La+iF3xMtaO9C1u8tXLm75+bCgT0NbyyEKwmBnGKMZ6WVMZkE/G7eiKGZ9vuYLPeScLgCNM6mj2Othax2xgzR96MsosZz9LpK8MY6joqJejbHiIqxW/mfrDH2cjtIY8feM1ZZk5Q0wO0OXfxWrHPMEAC1te+iDfwZ5UiKoqPgb+iwtPDdTn2Tk4A0Dqg2UNNXcWOGFtW9GzxeuhJqM89cMsrIKxn0+MGhLJvwCFFNBUfyYmThyvFMzh8YALAtST0aD/EZ2HwtKg+m+cRgliwYpo91j0YEzkx0w9VYS3DNqbeKhBX1fyahq4263SjI+CaZJ7rWeZ0pdK49AUpPMsBjphrnrGKp35X8wuegvwrW1pZlReMypKx3WHFzXMiZPCQRGLC719WO4zMmhzX/eqFqdz1Ib0hHDQZw6ZhpOesEjo7TBMZaY=
