git:
  depth: 10

os:
  - osx

language: node_js
node_js:
  - "6.7.0"

install:
  - npm install
  - cd script && npm install && cd ..
  - sh travis_before_script.sh

script:
  script/build

cache:
  directories:
    - electron
    - node_modules
    - apm/node_modules
    - script/node_modules
    - ~/.thera/compile-cache

notifications:
  email:
    recipients:
      - huc1011@gmail.com
      - hzdengxu@163.com
      - 1032419360@qq.com
      - dutlxq2014@163.com
    on_success: always
    on_failure: always
